name: raspisanie
description: Приложение для просмотра расписания Университетского колледжа ОГУ.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.9+12

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Internet connection checker.
  # See https://pub.dev/packages/internet_connection_checker
  internet_connection_checker: ^0.0.1+3

  # Widgets that make it easy to implement the BLoC.
  # See https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3

  # Helps to implement value based equality without explicitly
  # override == and hashCode.
  # See https://pub.dev/packages/equatable
  equatable: ^2.0.3

  # Functional Programming in Dart
  # See https://pub.dev/packages/dartz/versions/0.10.0-nullsafety.2
  dartz: ^0.10.0-nullsafety.2

  # A highly customizable autocomplete text input field for Flutter
  # See https://pub.dev/packages/flutter_typeahead
  flutter_typeahead: ^4.0.0

  # The Font Awesome Icon pack available as Flutter Icons.
  # Provides 1600 additional icons to use in your apps.
  # See https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^10.1.0

  # Table calendar for schedule
  # See https://pub.dev/packages/table_calendar
  table_calendar: ^3.0.6

  # Creates page that is dismissed by swipe gestures, with Hero style
  # animations, Inspired by Facebook, Instagram stories.
  # See https://pub.dev/packages/dismissible_page
  # dismissible_page: ^0.7.2

  # Simple no-sql local database.
  # See https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.11

  auto_route: ^5.0.1

  flutter_inner_drawer:
    git:
      url: https://github.com/0niel/flutter_inner_drawer.git
      ref: bugfix/type-casting

  # A Flutter plugin for launching a URL. Supports iOS, Android, web, Windows, macOS, and Linux.
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.17

  salomon_bottom_bar: ^3.2.0

  introduction_screen: ^3.0.2

  html: ^0.15.0

  http: ^0.13.4

  # Get version name in runtime
  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^1.4.2

  # Simple direct Service Locator for Dependency Injection.
  # See https://pub.dev/packages/get_it
  get_it: ^7.2.0

  # Allows dynamically change between light and dark theme.
  # See https://pub.dev/packages/adaptive_theme
  adaptive_theme: ^3.0.0

  settings_ui: ^2.0.2

  flutter_slidable: ^2.0.0

  # after_layout: ^1.1.0
  # get:
  # get_storage:

  # https://pub.dev/packages/home_widget
  home_widget: ^0.1.5

  # https://pub.dev/packages/restart_app
  restart_app: ^1.1.0+1

  # freezed_annotation: ^2.0.3
  firebase_core: ^1.12.0
  # firebase_app_check: ^0.0.6+8
  firebase_database: ^9.0.9
  firebase_crashlytics: ^2.5.1
  firebase_analytics: ^9.1.3
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  firebase_messaging: ^13.0.1
  firebase_in_app_messaging: ^0.6.0+22

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.1.1

  bloc_test: ^9.0.3
  mocktail: ^0.3.0

  integration_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  auto_route_generator: ^5.0.2
  build_runner:

flutter_icons:
  image_path: "assets/icons/icon_dark.png"
  android: true
  ios: true
  adaptive_icon_background: 'assets/icons/ic_launcher_background_dark.png'
  adaptive_icon_foreground: 'assets/icons/ic_launcher_foreground_dark.png'

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/icons/ic_launcher_foreground_light.png'
  color_dark: "#0F0E13"
  image_dark: 'assets/icons/ic_launcher_foreground_dark.png'

  android_12:
    color: '#FFFFFF'
    image: 'assets/icons/ic_launcher_foreground_light.png'
    color_dark: "#0F0E13"
    image_dark: 'assets/icons/ic_launcher_foreground_dark.png'

  web: false
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
